
## Progress Report ##


```{r}
library(tidyverse)
library(broom)
library(ggplot2)
library(ggthemes)
```

### Sam's Part Start ###

```{r, message = FALSE}
scoreboard = read_csv("../data/scoreboard.csv")
```



```{r}
namefile = names(scoreboard)
```

```{r}
institution_names = four_year_institution$Institution
```



**Find the earnings variables**
```{r}
data.frame(namefile) %>%
  filter(str_detect(namefile, "GT_"))
```

**Find the retention variables**
```{r}
data.frame(namefile) %>%
  filter(str_detect(namefile, "RET_"))
```



**Select the variables from retention rates and earnings**
```{r}
scoreboard %>%
  dplyr::select(c("INSTNM", "CITY", "STABBR", "ZIP", "INSTURL", "RET_FT4", "RET_FTL4", "RET_PT4", "RET_PTL4", "RET_FT4_POOLED", "RET_FTL4_POOLED", "RET_PT4_POOLED", "RET_PTL4_POOLED", "POOLYRSRET_FT", "POOLYRSRET_PT", "GT_28K_P6", "GT_28K_P8", "GT_28K_P10")) %>%
  rename("Institution" = 1, "City" = 2, "State" = 3, "Zip" = 4, "url" = 5, "Fulltime-Four-Retention" = 6, "Full-Less-Four-Retention" = 7, "Part-Four-Retention" = 8, "Part-Less-Four-Retention" = 9, "Full-Four-Pooled-Variance" = 10, "Full-Less-Four-Pooled-Variance" = 11, "Part-Four-Pooled-Variance" = 12, "Part-Less-Four-Pooled-Variance" = 13, 
"Full-Cohort" = 14, "Part-Cohort" = 15, "Earnings after 6 years" = 16, "Earnings after 8 years" = 17, "Earnings after 10 years" = 18) ->
  retention_scoreboard
```



```{r}
retention_scoreboard
```


**Filter out the NULL values**
```{r}
retention_scoreboard %>%
  select("Institution", "Fulltime-Four-Retention", "Part-Four-Retention", "Earnings after 6 years", "Earnings after 8 years", "Earnings after 10 years", "City", "State", "Zip", "url") %>%
  filter(`Fulltime-Four-Retention` != "NULL") %>%
  filter(`Part-Four-Retention` != "NULL") ->
  four_year_institution_retention
```


**Clean the data**
```{r}
four_year_institution_retention %>%
  rename("FullTime" = 2, "PartTime" = 3) %>%
 gather("FullTime", "PartTime", key = "Type", value = "Retention") %>%
  filter(`Earnings after 6 years` != "PrivacySuppressed") %>%
  mutate(Retention = as.numeric(Retention)) %>%
  mutate(`Earnings after 6 years` = as.numeric(`Earnings after 6 years`)) %>%
  mutate(`Earnings after 8 years` = as.numeric(`Earnings after 8 years`)) %>%
  mutate(`Earnings after 10 years` = as.numeric(`Earnings after 10 years`)) ->
  
  four_year_institution
```



```{r}
names(four_year_institution)
```

```{r}
four_year_institution %>%
  select("Earnings after 6 years", "Earnings after 8 years", "Earnings after 10 years", "State", "Type", "Retention") ->
  four_year_data
```





## Sam's Shiny ##
```{r}
library(shiny)


ui <- fluidPage(
  titlePanel("Earnings and Retentions in Four-Year Institutions"), 
  sidebarLayout(
    sidebarPanel(
  varSelectInput("var1", "Variable 1", data = four_year_data),
  checkboxInput("log2", "Log"), 
  varSelectInput("var2", "Variable 2", data = four_year_data),
  checkboxInput("log3", "Log"), 
  checkboxInput("ols", "OLS!"), 
  varSelectInput("var3", "Variable 3", data = four_year_data), 
  sliderInput("bins", "Bins", min = 1, max = 100, value = 20),
  checkboxInput("log4", "Log"), 
  textInput("text1", "Institution"), 
  checkboxInput("parttime", "Part Time"), 
  checkboxInput("fulltime", "Full Time")
  ), 
  
  mainPanel(
    fluidRow(
      splitLayout(cellWidths = c("300px", "300px"), plotOutput("scatter"), plotOutput("hist"))), 
  column(12, dataTableOutput("ttest", width = "300px", height = "5px")), 
  column(11, dataTableOutput("table", width = "300px", height = "5px")), 
  )
))


server <- function(input, output, session) {
  
   df = reactive({
      four_year_institution %>%
        filter(Institution == input$text1) ->
        k
        return(k)
    })
  
  
  
  
  output$table = renderDataTable({
      if(input$parttime == TRUE & input$fulltime == FALSE) {
    
    return(df() %>%
             filter(Type == "PartTime"))
      }
      
      if(input$fulltime == TRUE & input$parttime == FALSE) {
        return(df() %>%
                 filter(Type == "FullTime"))
      }
        
     
      
      else {
          return(df())
        }
    })
  
  
  
  output$scatter = renderPlot({
    if((class(four_year_data[[input$var1]]) == "numeric") & (class(four_year_data[[input$var2]]) == "numeric")){
      
    p = ggplot(four_year_data, aes(x = !!input$var1, y = !!input$var2)) + 
      geom_point() + 
      theme_bw()
    
    if(input$log2 == TRUE) {
      p = p + scale_x_log10()
    }
    
    if(input$log3 == TRUE) {
      p = p + scale_y_log10()
    }
    if(input$ols == TRUE) {
      p = p + geom_smooth(method = "lm", se = F)
    }
    
    return(p)
    }
    
    if((class(four_year_data[[input$var1]]) == "character" & class(four_year_data[[input$var2]]) == "numeric")) {
   p = ggplot(four_year_data, aes(x = !!input$var1, y = !!input$var2)) +     
   geom_boxplot() + 
   theme_bw()
   if(input$log3 == TRUE) {
      p = p + scale_y_log10()
    }
    
    return(p)
   }
  
  
  if((class(four_year_data[[input$var1]]) == "numeric" & class(four_year_data[[input$var2]]) == "character")) {
   p = ggplot(four_year_data, aes(x = !!input$var2, y = !!input$var1)) +     
    geom_boxplot() + 
    theme_bw() + 
     coord_flip()
    
    if(input$log2 == TRUE) {
     p = p + scale_y_log10()
    }
    
   return(p)
  }
  
  if((class(four_year_data[[input$var1]]) == "character" & class(four_year_data[[input$var2]]) == "character")) {
    p = ggplot(four_year_data, aes(x = !!input$var2, y = !!input$var1))+ 
    geom_jitter(stat = "identity") + 
    theme_bw()
    
    return(p)
  }
    
    
    
  })
  
  output$ttest = renderDataTable({
    if(class(four_year_data[[input$var1]]) == "numeric" & class(four_year_data[[input$var2]]) == "numeric") {
      df1 = reactive({
        t.test(four_year_data[[input$var1]], four_year_data[[input$var2]]) %>%
          tidy() %>%
          select(p.value, conf.low, conf.high) %>%
          rename("P.value" = 1, "Lower" = 2, "Upper" = 3) ->
          k
        return(k)
      })
      
      return(df1())
      
    }
    
    if(class(four_year_data[[input$var1]]) == "character" & class(four_year_data[[input$var2]]) == "numeric") {
      df2 = reactive({
        aov(four_year_data[[input$var2]] ~ four_year_data[[input$var1]]) %>%
          tidy() %>%
          
          filter(term == "four_year_data[[input$var1]]") %>%
          select(df, statistic, p.value) %>%
          rename("Degrees of Freedom" = 1, "Test Statistic" = 2, "P.value" = 3) ->
          m
         
        return(m)
      })
      return(df2())
    }
    
    
   
     if(class(four_year_data[[input$var2]]) == "character" & class(four_year_data[[input$var1]]) == "numeric") {
      df3 = reactive({
        aov(four_year_data[[input$var1]] ~ four_year_data[[input$var2]]) %>%
          tidy() %>%
          
          filter(term == "four_year_data[[input$var2]]") %>%
          select(df, statistic, p.value) %>%
          rename("Degrees of Freedom" = 1, "Test Statistic" = 2, "P.value" = 3) ->
          n
         
        return(n)
      })
      return(df3())
    }
    
    
   
    
    
    
  })
  
output$hist = renderPlot({
  
   if (class(four_year_data[[input$var3]]) == "numeric"){
        if(input$log4 == TRUE) {
          
         ggplot(four_year_data, aes(log(x = four_year_data[[input$var3]]))) + 
         geom_histogram(bins = input$bins, color = "black", fill = "white") + 
         theme_bw() + 
            labs(x = input$var3, y = "count")}
        
        else {
          ggplot(four_year_data, aes(x = four_year_data[[input$var3]])) + 
            geom_histogram(bins = input$bins, color = "black", fill = "white") + 
            theme_bw() + 
            labs(x = input$var3, y = "count")
        }
      }
    
      else {
        if(input$log4 == TRUE) {
          
      
        ggplot(data.frame(table(four_year_data[[input$var3]])), aes(x = Var1, y =          log(Freq))) + 
        geom_bar(stat = "identity", color = "black", fill = "white") + 
        theme_bw() + 
        labs(x = input$var3, y = "frequency")
        
        }
        
        else {
          ggplot(data.frame(table(four_year_data[[input$var3]])), aes(x = Var1, y =           Freq)) + 
          geom_bar(stat = "identity", color = "black", fill = "white") + 
            theme_bw() + 
            labs(x = input$var1, y = "frequency")
        }
          
      
      }
    })
}
shinyApp(ui, server)

```



```{r}
k
```


```{r}
t.test(four_year_data$`Earnings after 6 years`, four_year_data$`Earnings after 10 years`) %>%
  tidy() %>%
  select(p.value, conf.low, conf.high) %>%
  rename("P.value" = 1, "Lower" = 2, "Upper" = 3) #->
         #tidy_df
```

```{r}
tidy_df
```

```{r}
aov(four_year_data[["Earnings after 6 years"]] ~ four_year_data[["State"]]) %>%
  tidy() ->
  df

```

```{r}
df %>%
  setNames(as.character(df[1,]))
```

```{r}
name.vec = paste("Hello",  "World")

aov(four_year_data$`Earnings after 6 years` ~ four_year_data$State) %>%
  tidy() %>%
  rename( name.vec = 1)
  
  
```

```{r}
name.vec
```

```{r}
paste("State", "degrees of freedom")
```


```{r}
tidy_df
```



```{r}
class(four_year_institution$`Earnings after 6 years`)
```

```{r}
class(four_year_institution$Retention)
```

















### AI's Part Start ###

```{r}
scoreboard %>% 
  select(INSTNM,CONTROL,INC_PCT_LO, INC_PCT_M1,INC_PCT_M2, INC_PCT_H1, INC_PCT_H2, DEP_INC_AVG, DEP_INC_N, DEP_INC_PCT_LO, DEP_INC_PCT_M1, DEP_INC_PCT_M2, DEP_INC_PCT_H1, DEP_INC_PCT_H2, IND_INC_AVG, IND_INC_N, IND_INC_PCT_LO, IND_INC_PCT_M1, IND_INC_PCT_M2, IND_INC_PCT_H1, IND_INC_PCT_H2) %>% 
  mutate(CONTROL = as.character(CONTROL),
         INC_PCT_LO = as.numeric(INC_PCT_LO),
         INC_PCT_M1 = as.numeric(INC_PCT_M1),
         INC_PCT_M2 = as.numeric(INC_PCT_M2),
         INC_PCT_H1 = as.numeric(INC_PCT_H1),
         INC_PCT_H2 = as.numeric(INC_PCT_H2),
         DEP_INC_AVG = as.numeric(DEP_INC_AVG),
         DEP_INC_N = as.numeric(DEP_INC_N),
         DEP_INC_PCT_LO = as.numeric(DEP_INC_PCT_LO),
         DEP_INC_PCT_M1 = as.numeric(DEP_INC_PCT_M1),
         DEP_INC_PCT_M2 = as.numeric(DEP_INC_PCT_M2),
         DEP_INC_PCT_H1 = as.numeric(DEP_INC_PCT_H1),
         DEP_INC_PCT_H2 = as.numeric(DEP_INC_PCT_H2),
         IND_INC_AVG = as.numeric(IND_INC_AVG),
         IND_INC_N = as.numeric(IND_INC_N),
         IND_INC_PCT_LO = as.numeric(IND_INC_PCT_LO),
         IND_INC_PCT_M1 = as.numeric(IND_INC_PCT_M1),
         IND_INC_PCT_M2 = as.numeric(IND_INC_PCT_M2),
         IND_INC_PCT_H1 = as.numeric(IND_INC_PCT_H1),
         IND_INC_PCT_H2 = as.numeric(IND_INC_PCT_H2)) %>% 
   mutate(CONTROL = replace(CONTROL, CONTROL == "1", "1-public"),
         CONTROL = replace(CONTROL, CONTROL == "2", "2-private nonprofit"),
         CONTROL = replace(CONTROL, CONTROL == "3", "3-private for-profit"))->
  scoreboard1


## boxplot of INC_PCT_, group by university type

  scoreboard1 %>% 
  select(INSTNM:INC_PCT_H2) %>% 
  filter(!is.na(INC_PCT_LO),
         !is.na(INC_PCT_M1),
         !is.na(INC_PCT_M2),
         !is.na(INC_PCT_H1),
         !is.na(INC_PCT_H2)) %>% 
  group_by(CONTROL) %>% 
  gather(INC_PCT_LO : INC_PCT_H2, key = "quintiles", value = "pct") %>% 
  mutate(quintiles = replace(quintiles, quintiles == "INC_PCT_LO", "1_LOW"),
         quintiles = replace(quintiles, quintiles == "INC_PCT_M1", "2_Median1"),
         quintiles = replace(quintiles, quintiles == "INC_PCT_M2", "3_Median2"),
         quintiles = replace(quintiles, quintiles == "INC_PCT_H1", "4_High1"),
         quintiles = replace(quintiles, quintiles == "INC_PCT_H2", "5_High2")) ->
   scoreboard1_INC
  
scoreboard1_INC %>% 
  ggplot(aes(x = quintiles, y = pct, fill = CONTROL))+
  geom_boxplot()+
  theme_bw()+
  scale_fill_colorblind()


## boxplot of independent 
scoreboard1 %>% 
  select(INSTNM,CONTROL,IND_INC_AVG, IND_INC_N, IND_INC_PCT_LO, IND_INC_PCT_M1, IND_INC_PCT_M2, IND_INC_PCT_H1, IND_INC_PCT_H2) %>% 
  filter(!is.na(IND_INC_AVG),
         !is.na(IND_INC_N),
         !is.na(IND_INC_PCT_LO),
         !is.na(IND_INC_PCT_M1),
         !is.na(IND_INC_PCT_M2),
         !is.na(IND_INC_PCT_H1),
         !is.na(IND_INC_PCT_H2)) %>% 
  group_by(CONTROL) %>% 
  gather(IND_INC_PCT_LO : IND_INC_PCT_H2, key = "quintiles", value = "pct") %>%
  mutate(quintiles = replace(quintiles, quintiles == "IND_INC_PCT_LO", "1_LOW"),
         quintiles = replace(quintiles, quintiles == "IND_INC_PCT_M1", "2_Median1"),
         quintiles = replace(quintiles, quintiles == "IND_INC_PCT_M2", "3_Median2"),
         quintiles = replace(quintiles, quintiles == "IND_INC_PCT_H1", "4_High1"),
         quintiles = replace(quintiles, quintiles == "IND_INC_PCT_H2", "5_High2")) ->
  scoreboard1_IND

scoreboard1_IND%>% 
  ggplot(aes(x = quintiles, y = pct, fill = CONTROL))+
  geom_boxplot()+
  theme_bw()+
  scale_fill_colorblind()

##boxplot of dependent
scoreboard1 %>% 
  select(INSTNM,CONTROL,DEP_INC_AVG, DEP_INC_N, DEP_INC_PCT_LO, DEP_INC_PCT_M1, DEP_INC_PCT_M2, DEP_INC_PCT_H1, DEP_INC_PCT_H2) %>% 
  filter(!is.na(DEP_INC_AVG),
         !is.na(DEP_INC_N),
         !is.na(DEP_INC_PCT_LO),
         !is.na(DEP_INC_PCT_M1),
         !is.na(DEP_INC_PCT_M2),
         !is.na(DEP_INC_PCT_H1),
         !is.na(DEP_INC_PCT_H2)) %>% 
  group_by(CONTROL) %>% 
  gather(DEP_INC_PCT_LO : DEP_INC_PCT_H2, key = "quintiles", value = "pct") %>%
  mutate(quintiles = replace(quintiles, quintiles == "DEP_INC_PCT_LO", "1_LOW"),
         quintiles = replace(quintiles, quintiles == "DEP_INC_PCT_M1", "2_Median1"),
         quintiles = replace(quintiles, quintiles == "DEP_INC_PCT_M2", "3_Median2"),
         quintiles = replace(quintiles, quintiles == "DEP_INC_PCT_H1", "4_High1"),
         quintiles = replace(quintiles, quintiles == "DEP_INC_PCT_H2", "5_High2"))->
  scoreboard1_DEP

scoreboard1_DEP%>% 
  ggplot(aes(x = quintiles, y = pct, fill = CONTROL))+
  geom_boxplot()+
  theme_bw()+
  scale_fill_colorblind()

## Boxplot of DEP_IND
scoreboard1 %>% 
  select(CONTROL, DEP_INC_AVG, IND_INC_AVG) %>% 
  filter(!is.na(DEP_INC_AVG),
         !is.na(IND_INC_AVG)) %>% 
  gather(DEP_INC_AVG:IND_INC_AVG, key = "DEP_IND", value = "AVG") %>% 
  group_by(CONTROL) %>% 
  ggplot(aes(x = DEP_IND, y = AVG, fill = CONTROL))+
  geom_boxplot()+
  theme_bw()+
  scale_fill_colorblind()


## Summary statistics:


```


### AI's part End ###






### Jack's part Start ###

```{r}
#cleaning data
# create a data that only contains Undergraduate Student Body by Race and    Gender for each school.
scoreboard %>%
  select(INSTNM, CONTROL,UGDS_MEN, UGDS_WOMEN, UGDS_WHITE, UGDS_BLACK,
         UGDS_HISP, UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR, UGDS_NRA,
         UGDS_UNKN) %>%
  mutate(UGDS_MEN = ifelse(UGDS_MEN == "NULL", NA, UGDS_MEN),
         UGDS_WOMEN = ifelse(UGDS_WOMEN == "NULL", NA, UGDS_WOMEN),
         UGDS_WHITE = ifelse(UGDS_WHITE == "NULL", NA, UGDS_WHITE),
         UGDS_BLACK = ifelse(UGDS_BLACK == "NULL", NA, UGDS_BLACK),
         UGDS_HISP = ifelse(UGDS_HISP == "NULL", NA, UGDS_HISP),
         UGDS_ASIAN = ifelse(UGDS_ASIAN == "NULL", NA, UGDS_ASIAN),
         UGDS_AIAN = ifelse(UGDS_AIAN == "NULL", NA, UGDS_AIAN),
         UGDS_NHPI = ifelse(UGDS_NHPI == "NULL", NA, UGDS_NHPI),
         UGDS_2MOR = ifelse(UGDS_2MOR == "NULL", NA, UGDS_2MOR),
         UGDS_NRA = ifelse(UGDS_NRA == "NULL", NA, UGDS_NRA),
         UGDS_UNKN = ifelse(UGDS_UNKN == "NULL", NA, UGDS_UNKN),
         UGDS_MEN = as.numeric(UGDS_MEN),
         UGDS_WOMEN = as.numeric(UGDS_WOMEN),
         UGDS_WHITE = as.numeric(UGDS_WHITE),
         UGDS_BLACK = as.numeric(UGDS_BLACK),
         UGDS_HISP  = as.numeric(UGDS_HISP),
         UGDS_ASIAN = as.numeric(UGDS_ASIAN),
         UGDS_AIAN = as.numeric(UGDS_AIAN),
         UGDS_NHPI = as.numeric(UGDS_NHPI), 
         UGDS_2MOR = as.numeric(UGDS_2MOR), 
         UGDS_NRA = as.numeric(UGDS_NRA),
         UGDS_UNKN = as.numeric(UGDS_UNKN)) %>%
  na.omit() -> 
  UGRG

#graph
#graph 
#UGRG %>%
  #gather(UGDS_MEN, UGDS_WOMEN, key = Gender, 
         #value = total_enrollment) %>%
  #ggplot(aes(x = UGDS_MEN,
             #y = total_enrollment)) +
  #geom_boxplot()


# plot the difference of population between men and women.
#it seems like women's populatino is more than men's population
UGRG %>%
  mutate(diff = UGDS_MEN - UGDS_WOMEN) %>%
  ggplot(aes(x = diff)) +
  geom_bar(width = 0.05) +
  xlab("difference population men and women")




#cleaning data
#average faculty salary vs the in-state tuition and fees or out-state tuition for each school. 

#new idea
#faculty's average salary versus instate or outstate tuition 
scoreboard %>%
  select(INSTNM, AVGFACSAL, TUITIONFEE_IN, TUITIONFEE_OUT) %>%
  mutate(AVGFACSAL = ifelse(AVGFACSAL == "NULL", NA, AVGFACSAL),
         TUITIONFEE_IN = ifelse(TUITIONFEE_IN == "NULL", NA, TUITIONFEE_IN),
         TUITIONFEE_OUT = ifelse(TUITIONFEE_OUT == "NULL", NA, TUITIONFEE_OUT),
         Ave_Faculty_Salary  = as.numeric(AVGFACSAL),
         TUITIONFEE_IN = as.numeric(TUITIONFEE_IN),
         TUITIONFEE_OUT = as.numeric(TUITIONFEE_OUT)) %>%
  na.omit() -> salary_tuition

#plot for average faculty salary with in state tuition fee
salary_tuition %>%
  ggplot(aes(x = Ave_Faculty_Salary,
             y = TUITIONFEE_IN)) +
  geom_point() +
  xlab("Average Faculty Salary") +
  ylab("In State Tuition")

#plot for average faculty salary with out state tuition fee
salary_tuition %>%
  ggplot(aes(x = Ave_Faculty_Salary,
             y = TUITIONFEE_OUT)) +
  geom_point() +
  xlab("Average Faculty Salary") +
  ylab("Out State Tuition")

#linear regression
library(broom)
lm(AVGFACSAL ~ TUITIONFEE_IN, data = salary_tuition) %>%
  tidy() %>%
  filter(p.value < 0.05)-> lmout_ST
```

### Jack's Part End ###

